name: b590prj
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - async-timeout=3.0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - bcrypt=3.1.7
  - blas=1.0
  - bleach=3.1.0
  - boto3=1.11.0
  - botocore=1.14.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.13.2
  - chardet=3.0.4
  - configargparse=0.14.0
  - cryptography=2.8
  - cudatoolkit=7.5
  - cudnn=5.1
  - cycler=0.10.0
  - datrie=0.8
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.15.2
  - dropbox=9.4.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - fftw=3.3.8
  - filechunkio=1.8
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - ftputil=3.4
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - ghostscript=9.22
  - giflib=5.1.4
  - gitdb2=2.0.6
  - gitpython=3.0.5
  - glib=2.63.1
  - gmp=6.1.2
  - gobject-introspection=1.56.1
  - google-api-core=1.16.0
  - google-auth=1.10.2
  - google-cloud-core=1.1.0
  - google-cloud-storage=1.24.1
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.6.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.8
  - idna_ssl=1.1.0
  - imagemagick=7.0.8_11
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=2.0.14
  - jbig=2.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jmespath=0.9.4
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.1
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp=0.5.2
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - multidict=4.7.3
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.4
  - nodejs=10.13.0
  - notebook=6.0.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.0
  - openslide=3.4.1
  - openslide-python=1.1.1
  - openssl=1.1.1g
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parallel=20200122
  - paramiko=2.6.0
  - parso=0.5.2
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - pixman=0.38.0
  - pkg-config=0.29.2
  - prettytable=0.7.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - protobuf=3.11.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pydicom=0.9.9
  - pygments=2.5.2
  - pygraphviz=1.3
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python-irodsclient=0.7.0
  - python_abi=3.6
  - pytz=2019.3
  - pyyaml=5.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.22.0
  - rsa=4.0
  - s3transfer=0.3.0
  - scikit-learn=0.22.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake=5.10.0
  - snakemake-minimal=5.10.0
  - sqlite=3.30.1
  - tensorflow-gpu=1.0.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toposort=1.5
  - tornado=6.0.3
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.6.9
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.4.2
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - deconvolution==1.0.0
    - scipy==1.1.0

