name: b590prj
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.1
  - appdirs=1.4.3
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcrypt=3.1.7
  - blas=1.0
  - boto3=1.7.84
  - botocore=1.10.84
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - cachetools=2.1.0
  - cairo=1.14.6
  - certifi=2019.9.11
  - cffi=1.13.2
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.8
  - datrie=0.8
  - decorator=4.4.1
  - docutils=0.15.2
  - dropbox=7.3.1
  - fftw=3.3.8
  - filechunkio=1.6
  - fontconfig=2.12.1
  - freetype=2.7
  - ftputil=3.2
  - gdk-pixbuf=2.36.9
  - gettext=0.19.8.1
  - ghostscript=9.18
  - giflib=5.1.7
  - gitdb2=2.0.6
  - gitpython=3.0.4
  - glib=2.51.4
  - gobject-introspection=1.51.3
  - google-api-core=1.14.1
  - google-auth=1.2.1
  - google-cloud-core=1.0.3
  - google-cloud-storage=1.20.0
  - google-resumable-media=0.3.2
  - googleapis-common-protos=1.6.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - harfbuzz=1.4.3
  - icu=58.2
  - idna=2.8
  - idna_ssl=1.1.0
  - imagemagick=7.0.7
  - importlib_metadata=0.23
  - jbig=2.1
  - jinja2=2.10.3
  - jmespath=0.9.4
  - jpeg=9c
  - jsonschema=3.1.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.34
  - libprotobuf=3.10.1
  - libtiff=4.0.9
  - libwebp=0.5.2
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=8.0.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - mock=3.0.5
  - more-itertools=7.2.0
  - multidict=4.5.2
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.13.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openslide=3.4.1
  - openslide-python=1.1.1
  - openssl=1.1.1d
  - pandas=0.24.2
  - pango=1.40.4
  - paramiko=2.6.0
  - pcre=8.43
  - perl=5.22.2.1
  - pillow=4.2.1
  - pip=19.3.1
  - pixman=0.34.0
  - pkg-config=0.29.2
  - prettytable=0.7.2
  - protobuf=3.10.1
  - psutil=5.6.5
  - pthread-stubs=0.4
  - pyasn1=0.4.7
  - pyasn1-modules=0.0.5
  - pycparser=2.19
  - pydicom=0.9.9
  - pygments=2.4.2
  - pygraphviz=1.3.1
  - pynacl=1.3.0
  - pyrsistent=0.15.5
  - pysftp=0.2.9
  - python=3.6.7
  - python-dateutil=2.8.1
  - python-irodsclient=0.7.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.13.0
  - rsa=3.1.4
  - s3transfer=0.1.13
  - scipy=0.19.1
  - setuptools=41.6.0
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake=5.7.4
  - snakemake-minimal=5.7.4
  - sqlite=3.30.1
  - tensorflow=1.0.0
  - tk=8.6.9
  - typing_extensions=3.7.4.1
  - urllib3=1.12
  - wheel=0.33.6
  - wrapt=1.11.2
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.3

